import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import * as XLSX from "xlsx";
import { FieldValue, getFirestore } from "firebase-admin/firestore";
import { getApps, initializeApp } from "firebase-admin/app";
import type { VehicleStatus } from "../packages/domain/src/types";

type Issue = { row: number; severity: "error" | "warning"; field: string; message: string };
type ImportVehicle = { id: string; sourceRow: number; registrationNumber: string; make: string; model: string; year: number | null; color: string | null; vin: string | null; lastServiceAt: string | null; insuranceExpiresAt: string | null; rates: { currency: "USD"; dailyCents: number | null; weeklyCents: number | null; monthlyCents: null } };
const SOURCE_NAME = "FleetDesk Inventory.xlsx";
const headers = ["Registraion No", "Make", "Model ", "VIN No.", "Year ", "Color", "Last Service Date", "Insurance Expiration ", "Daily ", "Weekly "];

function argument(name: string): string | undefined { const exact = process.argv.indexOf(name); if (exact !== -1) return process.argv[exact + 1]; const inline = process.argv.find((value) => value.startsWith(`${name}=`)); return inline?.slice(name.length + 1); }
function has(name: string): boolean { return process.argv.includes(name); }
function text(value: unknown): string | null { const normalized = String(value ?? "").trim(); return normalized ? normalized : null; }
function asCents(value: unknown, row: number, field: string, issues: Issue[]): number | null { if (value === null || value === undefined || value === "") { issues.push({ row, severity: "warning", field, message: "Missing rate" }); return null; } const number = typeof value === "number" ? value : Number(String(value).replace(/[$,]/g, "")); if (!Number.isFinite(number) || number < 0) { issues.push({ row, severity: "error", field, message: "Rate must be a non-negative number" }); return null; } return Math.round(number * 100); }
function asDate(value: unknown, row: number, field: string, issues: Issue[]): string | null { if (!value) { issues.push({ row, severity: "warning", field, message: "Missing date" }); return null; } const date = value instanceof Date ? value : new Date(String(value)); if (Number.isNaN(date.valueOf())) { issues.push({ row, severity: "error", field, message: "Invalid date" }); return null; } return date.toISOString(); }
function documentId(registration: string): string { return `vehicle_${registration.toUpperCase().replace(/[^A-Z0-9]+/g, "_").replace(/^_|_$/g, "")}`; }

function parseWorkbook(file: string): { vehicles: ImportVehicle[]; issues: Issue[] } {
  const workbook = XLSX.readFile(file, { cellDates: true, raw: true }); const sheet = workbook.Sheets.INVENTORY; if (!sheet) throw new Error("Expected an INVENTORY worksheet."); const rows = XLSX.utils.sheet_to_json<unknown[]>(sheet, { header: 1, defval: null, raw: true }); const issues: Issue[] = []; const foundHeaders = (rows[1] ?? []).map((cell) => String(cell ?? "")); if (!headers.slice(0, 8).every((header, index) => foundHeaders[index] === header)) issues.push({ row: 2, severity: "error", field: "headers", message: "Workbook layout does not match the approved INVENTORY schema" });
  const registrations = new Set<string>(); const vins = new Map<string, number>(); const vehicles: ImportVehicle[] = [];
  for (let index = 3; index < rows.length; index += 1) { const row = rows[index]; if (!row?.some((value) => value !== null && value !== "")) continue; const sourceRow = index + 1; const registration = text(row[0])?.toUpperCase() ?? null; const make = text(row[1])?.toUpperCase() ?? null; const model = text(row[2]); const vin = text(row[3])?.toUpperCase() ?? null; const yearValue = row[4] === null || row[4] === "" ? null : Number(row[4]); const year = Number.isInteger(yearValue) ? yearValue : null;
    if (!registration) issues.push({ row: sourceRow, severity: "error", field: "registrationNumber", message: "Registration number is required" }); else if (registrations.has(registration)) issues.push({ row: sourceRow, severity: "error", field: "registrationNumber", message: `Duplicate registration number ${registration}` }); else registrations.add(registration);
    if (!make) issues.push({ row: sourceRow, severity: "error", field: "make", message: "Make is required" }); if (!model) issues.push({ row: sourceRow, severity: "error", field: "model", message: "Model is required" }); if (year === null) issues.push({ row: sourceRow, severity: "warning", field: "year", message: "Missing or invalid year" }); else if (year < 1886 || year > new Date().getUTCFullYear() + 1) issues.push({ row: sourceRow, severity: "error", field: "year", message: "Year is outside valid vehicle range" });
    if (!vin) issues.push({ row: sourceRow, severity: "warning", field: "vin", message: "VIN is missing; vehicle must be verified before rental" }); else if (vin.length !== 17 || /[IOQ]/.test(vin)) issues.push({ row: sourceRow, severity: "warning", field: "vin", message: "VIN format should be physically verified" }); else { const originalRow = vins.get(vin); if (originalRow) issues.push({ row: sourceRow, severity: "error", field: "vin", message: `Duplicate VIN; first seen at row ${originalRow}` }); else vins.set(vin, sourceRow); }
    if (registration && make && model) vehicles.push({ id: documentId(registration), sourceRow, registrationNumber: registration, make, model, year, color: text(row[5]), vin, lastServiceAt: asDate(row[6], sourceRow, "lastServiceAt", issues), insuranceExpiresAt: asDate(row[7], sourceRow, "insuranceExpiresAt", issues), rates: { currency: "USD", dailyCents: asCents(row[8], sourceRow, "dailyRate", issues), weeklyCents: asCents(row[9], sourceRow, "weeklyRate", issues), monthlyCents: null } });
  }
  return { vehicles, issues };
}

async function main(): Promise<void> {
  const file = argument("--file"); if (!file) throw new Error("Usage: pnpm import:inventory -- --file <workbook.xlsx> [--commit --allow-warnings --initial-status=available]"); const initialStatus = (argument("--initial-status") ?? "out_of_service") as VehicleStatus; if (!["available", "out_of_service"].includes(initialStatus)) throw new Error("Initial status must be available or out_of_service.");
  const sourceBytes = await readFile(file); const sourceHash = createHash("sha256").update(sourceBytes).digest("hex"); const migrationId = `inventory_${sourceHash.slice(0, 20)}`; const { vehicles, issues } = parseWorkbook(file); const report = { migrationId, source: path.basename(file), sourceHash, parsedAt: new Date().toISOString(), dryRun: !has("--commit"), initialStatus, vehicles: vehicles.length, errorCount: issues.filter((issue) => issue.severity === "error").length, warningCount: issues.filter((issue) => issue.severity === "warning").length, issues };
  await mkdir("reports", { recursive: true }); const reportFile = path.join("reports", `${migrationId}.json`); await writeFile(reportFile, `${JSON.stringify(report, null, 2)}\n`, "utf8"); console.log(JSON.stringify({ ...report, issues: undefined, reportFile }, null, 2));
  if (!has("--commit")) return; if (report.errorCount) throw new Error(`Import blocked: ${report.errorCount} validation error(s). Review ${reportFile}.`); if (report.warningCount && !has("--allow-warnings")) throw new Error(`Import has ${report.warningCount} warning(s). Review and rerun with --allow-warnings only after verification.`);
  if (!getApps().length) initializeApp(); const db = getFirestore(); const migrationRef = db.collection("imports").doc(migrationId); const previous = await migrationRef.get(); if (previous.exists && previous.get("status") === "completed") throw new Error(`Migration ${migrationId} has already completed. It is intentionally not re-applied.`);
  await migrationRef.set({ migrationId, source: path.basename(file), sourceHash, status: "in_progress", initialStatus, totalVehicles: vehicles.length, reportFile, startedAt: FieldValue.serverTimestamp() }, { merge: true });
  for (let offset = 0; offset < vehicles.length; offset += 400) { const batch = db.batch(); for (const vehicle of vehicles.slice(offset, offset + 400)) { batch.set(db.collection("vehicles").doc(vehicle.id), { registrationNumber: vehicle.registrationNumber, make: vehicle.make, model: vehicle.model, year: vehicle.year, color: vehicle.color, vin: vehicle.vin, registrationExpiresAt: null, insuranceExpiresAt: vehicle.insuranceExpiresAt, lastServiceAt: vehicle.lastServiceAt, nextServiceDueAt: null, rates: vehicle.rates, status: initialStatus, notes: `Imported from ${SOURCE_NAME}, row ${vehicle.sourceRow}. Verify missing/flagged fields before assigning.`, photoPaths: [], import: { migrationId, sourceRow: vehicle.sourceRow }, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }, { merge: false }); } await batch.commit(); }
  await migrationRef.set({ status: "completed", completedAt: FieldValue.serverTimestamp(), importedVehicles: vehicles.length }, { merge: true }); console.log(`Completed ${migrationId}: ${vehicles.length} vehicles imported as ${initialStatus}.`);
}
main().catch((error) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; });
